In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import quantile_transform
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import OneHotEncoder  ##. better to use dummy from pandas 
from sklearn.preprocessing import PowerTransformer
from scipy.stats import boxcox
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from scipy.stats import boxcox
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
pd.options.display.max_rows = 50

/Users/christineiskander/opt/anaconda3/envs/DA_Env/lib/python3.9/site-packages/statsmodels/compat/pandas.py:61: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex


In [2]:
df_customer = pd.read_csv("Data_Marketing_Customer_Analysis_Round3.csv")
df_customer

Unnamed: 0       region  customer_lifetime_value response  coverage  \
0               0      central                     4809       no     basic   
1               1  west region                     2228       no     basic   
2               2         east                    14947       no     basic   
3               3   north west                    22332      yes  extended   
4               4   north west                     9025       no   premium   
...           ...          ...                      ...      ...       ...   
10684       10684      central                    15563       no   premium   
10685       10685   north west                     5259       no     basic   
10686       10686      central                    23893       no  extended   
10687       10687  west region                    11971       no   premium   
10688       10688  west region                     6857       no     basic   

      education effective_to_date month employment_status gender  ...  \
0       college           2/18/11   feb          employed      m  ...   
1       college           1/18/11   jan        unemployed      f  ...   
2      bachelor           2/10/11   feb          employed      m  ...   
3       college           1/11/11   jan          employed      m  ...   
4      bachelor           1/17/11   jan     medical leave      f  ...   
...         ...               ...   ...               ...    ...  ...   
10684  bachelor           1/19/11   jan        unemployed      f  ...   
10685   college            1/6/11   jan          employed      f  ...   
10686  bachelor            2/6/11   feb          employed      f  ...   
10687   college           2/13/11   feb          employed      f  ...   
10688  bachelor            1/8/11   jan        unemployed      m  ...   

       months_since_policy_inception number_of_open_complaints  \
0                                 52                         0   
1                                 26                         0   
2                                 31                         0   
3                                  3                         0   
4                                 31                         1   
...                              ...                       ...   
10684                             40                         2   
10685                             68                         0   
10686                             63                         0   
10687                             27                         4   
10688                              1                         0   

      number_of_policies     policy_type        policy  renew_offer_type  \
0                      9  corporate auto  corporate l3            offer3   
1                      1   personal auto   personal l3            offer4   
2                      2   personal auto   personal l3            offer3   
3                      2  corporate auto  corporate l3            offer2   
4                      7   personal auto   personal l2            offer1   
...                  ...             ...           ...               ...   
10684                  7   personal auto   personal l1            offer3   
10685                  6   personal auto   personal l3            offer2   
10686                  2  corporate auto  corporate l3            offer1   
10687                  6   personal auto   personal l1            offer1   
10688                  3   personal auto   personal l1            offer4   

       sales_channel  total_claim_amount  vehicle_class vehicle_size  
0              agent                 292  four-door car      medsize  
1        call center                 744  four-door car      medsize  
2        call center                 480            suv      medsize  
3             branch                 484  four-door car      medsize  
4             branch                 707  four-door car      medsize  
...              ...                 ...            ...      

In [31]:
numerical=df_customer.select_dtypes(int)
numerical=numerical.drop("Unnamed: 0", axis=1)
numerical

customer_lifetime_value  income  monthly_premium_auto  \
0                         4809   48029                    61   
1                         2228   26794                    64   
2                        14947   22139                   100   
3                        22332   49078                    97   
4                         9025   23675                   117   
...                        ...     ...                   ...   
10684                    15563   64811                   253   
10685                     5259   61146                    65   
10686                    23893   39837                   201   
10687                    11971   64195                   158   
10688                     6857   88784                   101   

       months_since_last_claim  months_since_policy_inception  \
0                            7                             52   
1                            3                             26   
2                           34                             31   
3                           10                              3   
4                           15                             31   
...                        ...                            ...   
10684                        8                             40   
10685                        7                             68   
10686                       11                             63   
10687                        0                             27   
10688                       31                              1   

       number_of_open_complaints  number_of_policies  total_claim_amount  
0                              0                   9                 292  
1                              0                   1                 744  
2                              0                   2                 480  
3                              0                   2                 484  
4                              1                   7                 707  
...                          ...                 ...                 ...  
10684                          2                   7                1214  
10685                          0                   6                 273  
10686                          0                   2                 381  
10687                          4                   6                 618  
10688                          0                   3                1021  

[10689 rows x 8 columns]

In [34]:
X=numerical.drop('total_claim_amount', axis=1)
y=df_customer.total_claim_amount

In [21]:
# Train-test split.
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.30,random_state=123)

In [27]:
# Standardize the data (after the data split).

std_scaler=StandardScaler().fit(X_train)  
X_train_scaled=std_scaler.transform(X_train)

X_train_scaled

array([[-0.11021627, -1.2632667 , -0.67143823, ...,  1.36516733,
        -0.42619497, -0.40381143],
       [-0.42794064, -1.36853038, -0.72925469, ...,  1.68786198,
        -0.42619497,  0.84759702],
       [-0.5223013 ,  0.26299646,  0.48489091, ...,  0.50464827,
        -0.42619497, -0.82094758],
       ...,
       [-0.81132612, -1.16342071, -0.90270406, ..., -1.39566466,
        -0.42619497, -0.82094758],
       [ 2.25575772,  0.97656622, -0.78707115, ..., -1.61079442,
        -0.42619497, -0.40381143],
       [ 1.18923585, -0.01438919, -0.55580532, ...,  0.21780858,
         1.77676929, -0.40381143]])

In [24]:
X_train.shape

(7482, 7)

In [29]:
X_test_scaled=std_scaler.transform(X_test)
X_test_scaled

array([[-0.40967729, -0.94647238, -0.61362178, ...,  1.54444214,
        -0.42619497,  2.51614162],
       [-0.7597249 , -0.93254692, -0.64253   , ...,  0.755633  ,
         0.67528716, -0.82094758],
       [ 0.57248529, -1.22437973, -0.90270406, ...,  0.39708339,
        -0.42619497, -0.40381143],
       ...,
       [-0.79857077,  0.60844433, -0.58471355, ..., -1.18053489,
        -0.42619497, -0.82094758],
       [-0.42547654, -0.96649777, -0.81597938, ..., -1.61079442,
         0.67528716,  0.43046087],
       [-0.49881985, -0.94988352,  0.71615674, ..., -1.00126009,
        -0.42619497, -0.82094758]])

In [36]:
# Apply linear regression.
model=LinearRegression()
model.fit(X_train_scaled, y_train)


LinearRegression()

In [37]:
# Model Interpretation.
model.coef_

array([ -6.68834608, -31.81052402, 187.79209652,   2.18339325,
        -0.51888932,   2.01420164,  -2.21705934])

In [38]:
model.intercept_

433.0597433841219