1. Import the numpy package under the name np
2. Create a null vector of size 10
3. Create a null vector of size 10 but the fifth value which is 1

In [74]:
import numpy as np
vec=np.zeros(10)
vec[4]=1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49

In [75]:
new_vec=np.arange(10,50)
new_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5. Create a 3x3 matrix with values ranging from 0 to 8

In [76]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [77]:
np.nonzero((1,2,0,0,4,0))

(array([0, 1, 4]),)

7. Create a 3x3 identity matrix

In [78]:
identity_matrix=np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values

In [79]:
d=np.random.random((3,3,3))
d

array([[[0.81234651, 0.01955667, 0.23782747],
        [0.18081059, 0.53639747, 0.52448326],
        [0.27573983, 0.62725286, 0.79134847]],

       [[0.38058511, 0.16587473, 0.02072694],
        [0.51689342, 0.78939708, 0.74033709],
        [0.99552587, 0.17722825, 0.82183774]],

       [[0.33840334, 0.96906757, 0.57803661],
        [0.19311941, 0.61212322, 0.83507833],
        [0.21746159, 0.03008617, 0.44584123]]])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [80]:
x=np.random.random((10,10))
x

array([[0.93980198, 0.08855961, 0.57466275, 0.80034603, 0.30896384,
        0.58787648, 0.40831444, 0.48347145, 0.24751906, 0.10813898],
       [0.08658371, 0.20060866, 0.00787666, 0.7348794 , 0.22871958,
        0.21586223, 0.85461567, 0.55849291, 0.65121681, 0.79354624],
       [0.09402774, 0.87600863, 0.87846119, 0.29372068, 0.13688725,
        0.17927334, 0.19227255, 0.92557273, 0.06580327, 0.28332451],
       [0.35852177, 0.68668241, 0.12644437, 0.26872658, 0.44326184,
        0.3945672 , 0.08509473, 0.06831314, 0.98820639, 0.91517846],
       [0.46927356, 0.33431628, 0.56252052, 0.50636529, 0.97995448,
        0.48388544, 0.83580283, 0.44455454, 0.67949418, 0.670519  ],
       [0.90282986, 0.72390981, 0.27324187, 0.97014303, 0.66635544,
        0.27304936, 0.87277577, 0.16056643, 0.82546213, 0.61017364],
       [0.29548952, 0.84169606, 0.34136433, 0.02985761, 0.19479327,
        0.97267878, 0.52367882, 0.39884686, 0.45056019, 0.72441047],
       [0.67291871, 0.18311665, 0.8701857

In [81]:
print(np.amax(x),np.amin(x))

0.9882063917586862 0.007876656883005095


10. Create a random vector of size 30 and find the mean value

In [82]:
rand_vec=np.random.random(30)
rand_vec

array([0.46443777, 0.33736331, 0.84058083, 0.84653864, 0.17046319,
       0.82036664, 0.01169826, 0.53667064, 0.51756101, 0.64858953,
       0.07693892, 0.47646043, 0.84158552, 0.89930419, 0.41713168,
       0.6432358 , 0.59780492, 0.57276462, 0.95338071, 0.18487419,
       0.15760427, 0.75478212, 0.32061677, 0.83917117, 0.42240592,
       0.73057681, 0.4055209 , 0.78858218, 0.17119303, 0.02303131])

In [83]:
np.mean(rand_vec)

0.515707841938574

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [84]:
m=np.diag(np.arange(1,5), k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix 

In [92]:
c=np.random.random((5,5))
c

array([[0.63913829, 0.8768217 , 0.6957523 , 0.57321469, 0.93026023],
       [0.66675548, 0.5938222 , 0.42796707, 0.39449394, 0.32463842],
       [0.55325498, 0.23120263, 0.06662993, 0.96658589, 0.64276394],
       [0.63648023, 0.09440107, 0.70122817, 0.66165283, 0.07186673],
       [0.74574789, 0.41332772, 0.63456238, 0.50005035, 0.12934189]])

In [94]:
c=(c-(np.mean(c))/np.std(c))
c

array([[4.65592012, 4.89360352, 4.71253412, 4.58999652, 4.94704206],
       [4.6835373 , 4.61060403, 4.4447489 , 4.41127577, 4.34142025],
       [4.57003681, 4.24798446, 4.08341175, 4.98336772, 4.65954577],
       [4.65326205, 4.1111829 , 4.71801   , 4.67843466, 4.08864856],
       [4.76252972, 4.43010955, 4.65134421, 4.51683218, 4.14612372]])

13. How to find common values between two arrays?

In [97]:
array1=([1,2,3,4,5,6,7,8,9,])
array2=([3,11,12,13,9,14,15,16,7,18,20])
np.intersect1d(array1,array2)

array([3, 7, 9])

14. Create a random vector of size 10 and sort it
15. and replace the maximum value by 0 

In [137]:
f=np.random.random(10)
np.sort(f)

array([0.02022313, 0.35540705, 0.37660878, 0.55452614, 0.82445068,
       0.83285995, 0.85721435, 0.8607281 , 0.88278943, 0.90236499])

In [138]:
f[np.argmax(f)]=0
f

array([0.8607281 , 0.88278943, 0.37660878, 0.82445068, 0.55452614,
       0.02022313, 0.85721435, 0.35540705, 0.        , 0.83285995])

16. Subtract the mean of each row of a matrix

In [142]:
b = f-f.mean(axis=0,keepdims=True)
b

array([ 0.30424734,  0.32630867, -0.17987198,  0.26796992, -0.00195462,
       -0.53625763,  0.30073359, -0.20107371, -0.55648076,  0.27637919])

17. How to get the n largest values of an array

In [151]:
Z = np.arange(10000) 
np.random.shuffle(Z) 
n = 5
Z[np.argsort(Z)[-n:]]

array([9995, 9996, 9997, 9998, 9999])

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

In [195]:
t=np.arange(1,16).reshape(5,3)
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [196]:
np.where(t>4,t**2,t)

array([[  1,   2,   3],
       [  4,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225]])