1. Import the numpy package under the name np
2. Create a null vector of size 10
3. Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np
vec=np.zeros(10)
vec[4]=1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49

In [2]:
new_vec=np.arange(10,50)
new_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
np.nonzero((1,2,0,0,4,0))

(array([0, 1, 4]),)

7. Create a 3x3 identity matrix

In [5]:
identity_matrix=np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values

In [6]:
d=np.random.random((3,3,3))
d

array([[[0.86109328, 0.91617961, 0.98161977],
        [0.94417784, 0.00916776, 0.59035357],
        [0.70961723, 0.90894892, 0.88218909]],

       [[0.34762809, 0.74679432, 0.4195588 ],
        [0.02086828, 0.92260891, 0.10971974],
        [0.19727689, 0.69307766, 0.33571788]],

       [[0.65877688, 0.92830048, 0.47266665],
        [0.98640599, 0.28891298, 0.89370983],
        [0.89040054, 0.74705461, 0.98673587]]])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [7]:
x=np.random.random((10,10))
x

array([[0.57258265, 0.12116427, 0.49309166, 0.65152471, 0.93140652,
        0.37106219, 0.86555307, 0.11694963, 0.65049602, 0.86670345],
       [0.98533205, 0.2980948 , 0.60876127, 0.93186957, 0.46063537,
        0.67810509, 0.95360887, 0.1128844 , 0.10331809, 0.98996422],
       [0.17937912, 0.87673846, 0.8803843 , 0.84692113, 0.37773359,
        0.1434256 , 0.35997901, 0.99436134, 0.45233681, 0.08700658],
       [0.38222852, 0.60231865, 0.38612447, 0.03500948, 0.62250837,
        0.31280467, 0.17159783, 0.46680124, 0.70436263, 0.45416409],
       [0.5033432 , 0.77405282, 0.42120305, 0.28159445, 0.17398029,
        0.73420696, 0.51835225, 0.12044373, 0.88730241, 0.13402657],
       [0.46069317, 0.75161   , 0.92315727, 0.95878008, 0.32897506,
        0.97563917, 0.20934333, 0.17250554, 0.5774761 , 0.0470452 ],
       [0.22577234, 0.50645664, 0.55056811, 0.20119591, 0.78037746,
        0.43839881, 0.91812719, 0.80751316, 0.82947091, 0.35790872],
       [0.76955658, 0.93162732, 0.2554008

In [8]:
print(np.amax(x),np.amin(x))

0.9943613354346879 0.001496263649796492


10. Create a random vector of size 30 and find the mean value

In [9]:
rand_vec=np.random.random(30)
rand_vec

array([0.50155566, 0.24295272, 0.07556939, 0.84701064, 0.66437338,
       0.83347678, 0.96224232, 0.86719541, 0.40071372, 0.69794275,
       0.05620853, 0.39401374, 0.10777315, 0.86683789, 0.764677  ,
       0.67325147, 0.34303075, 0.85647974, 0.76901173, 0.07522736,
       0.63478932, 0.83841727, 0.74223384, 0.03657312, 0.96119785,
       0.91412053, 0.60153252, 0.57951   , 0.68719781, 0.79149219])

In [10]:
np.mean(rand_vec)

0.5928869521027951

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [11]:
m=np.diag(np.arange(1,5), k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix 

In [12]:
c=np.random.random((5,5))
c

array([[0.81965426, 0.48309699, 0.67249336, 0.09862691, 0.25569824],
       [0.60902446, 0.30455827, 0.45407372, 0.86086725, 0.10246731],
       [0.40192221, 0.93695174, 0.56982896, 0.07713173, 0.29201226],
       [0.87856557, 0.76410124, 0.77633817, 0.61293354, 0.8563977 ],
       [0.11776716, 0.06106494, 0.21851359, 0.43989794, 0.68705261]])

In [13]:
c=(c-(np.mean(c))/np.std(c))
c

array([[-0.92449212, -1.26104939, -1.07165302, -1.64551948, -1.48844814],
       [-1.13512192, -1.43958811, -1.29007266, -0.88327913, -1.64167907],
       [-1.34222417, -0.80719464, -1.17431742, -1.66701465, -1.45213412],
       [-0.86558081, -0.98004515, -0.96780821, -1.13121284, -0.88774868],
       [-1.62637922, -1.68308145, -1.5256328 , -1.30424844, -1.05709377]])

13. How to find common values between two arrays?

In [14]:
array1=([1,2,3,4,5,6,7,8,9,])
array2=([3,11,12,13,9,14,15,16,7,18,20])
np.intersect1d(array1,array2)

array([3, 7, 9])

14. Create a random vector of size 10 and sort it
15. and replace the maximum value by 0 

In [15]:
f=np.random.random(10)
np.sort(f)

array([0.0184845 , 0.02082146, 0.19023424, 0.21310951, 0.34384771,
       0.68627935, 0.7732667 , 0.8370133 , 0.91840901, 0.94960807])

In [16]:
f[np.argmax(f)]=0
f

array([0.19023424, 0.68627935, 0.91840901, 0.7732667 , 0.8370133 ,
       0.        , 0.34384771, 0.21310951, 0.0184845 , 0.02082146])

16. Subtract the mean of each row of a matrix

In [17]:
b = f-f.mean(axis=0,keepdims=True)
b

array([-0.20991233,  0.28613277,  0.51826243,  0.37312012,  0.43686672,
       -0.40014658, -0.05629887, -0.18703707, -0.38166208, -0.37932511])

17. How to get the n largest values of an array

In [18]:
Z = np.arange(10000) 
np.random.shuffle(Z) 
n = 5
Z[np.argsort(Z)[-n:]]

array([9995, 9996, 9997, 9998, 9999])

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

In [19]:
t=np.arange(1,16).reshape(5,3)
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
np.where(t>4,t**2,t)

array([[  1,   2,   3],
       [  4,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225]])